
[package]
name = "executor"
version = "0.1.0"
edition = "2021"

[dependencies]
fyrox = { workspace = true }
my_game = { path = "../game", optional = true }

[features]
default = ["my_game"]
dylib = ["fyrox/dylib"]
